### ISSUE TITLE
geocoder control not working

### ISSUE THREAD

**Issue by Adriaanse** [openearth/vue2mapbox-gl#1]
If i add a geocoder control insite the v-mapbox element like this:

`<v-mapbox-geocoder></v-mapbox-geocoder>`

I only get a warning in the debug console:

[Vue warn]: Unknown custom element: <v-mapbox-geocoder> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Looking at the code i think it is missing in main js, work in progress ?

**Comment by SiggyF** [comment]
Thanks for your comment. I did not properly register the `v-mapbox-geocoder c` component.
