### ISSUE TITLE
Easy way to create markers?

### ISSUE THREAD

**Issue by doublemc** [openearth/vue2mapbox-gl#18]
Hey, like your lib - first one that actually works out of the box without any problems. I have a problem though - is there a way to add markers via this lib? 
THx!

**Comment by SiggyF** [comment]
Thanks. We'll prepare an example in the storybook.

**Comment by enzoftware** [comment]
any udpate?

**Comment by claudiomulas-flygo** [comment]
+1

**Comment by claudiomulas-flygo** [comment]
This is how I've done it:

Captured the event

`<v-mapbox @mb-created="mapCreated" />`

saved the map variable
```
mapCreated: function(map){
                console.log("map event", map);
                this.map = map;
            }
```
and then added the marker
`import mapboxgl from 'mapbox-gl';`

`this.point = new mapboxgl.Marker().setLngLat(this.currentPosition).addTo(this.map);`

**Comment by SiggyF** [comment]
This was added in #36
